version: '3.8'

services:
  booking-postgresdb:
    image: postgres:15
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: .
    depends_on:
      booking-postgresdb:
        condition: service_healthy
    environment:
      ConnectionStrings__BookingContext: "Host=booking-postgresdb;Port=5432;Database=mydatabase;Username=myuser;Password=mypassword"
    ports:
      - "5000:8080"
    restart: always

volumes:
  pgdata:
